### DISCUSSION TITLE
Example Usage with Docker Build and Keptn 0.10.0

### DISCUSSION THREAD

**Discussion by christian-kreuzberger-dtx** [keptn-sandbox/keptn-jenkins-library#64] [Show and tell]
Here is an example I made with version 5.1 of the library and Keptn 0.10.0.

*Note 1*: I have ommitted the files slo.yaml and sli.yaml - please refer to https://github.com/keptn/examples for those files
*Note 2*: I have also ommitted the helm chart files for hello-service.tgz - please refer to https://github.com/keptn/examples for examples

**index.js**
```javascript
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello World!');
});

var server = app.listen(3000, function () {
  var host = server.address().address;
  var port = server.address().port;

  console.log('Example app listening at http://%s:%s', host, port);
});
```

**Dockerfile**
```Dockerfile
FROM node:12.18.1-alpine

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY . .

EXPOSE 3000
CMD npm start
```

**Shipyard.yaml**
```yaml
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
            - name: "test"
              properties:
                teststrategy: "functional"
            - name: "evaluation"
```

**Jenkinsfile**
```groovy
@Library('keptn-library@5.1')_
def keptn = new sh.keptn.Keptn()


node('jenkins-slave') {

    def commit_id

    def image_name = "christiankreuzbergerdtx/docker-nodejs-demo"

    def project = "nodejs-example"
    def service = "hello-service"
    def firststage = "dev"

    stage('Preparation') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"                        
        commit_id = readFile('.git/commit-id').trim()
    }

    stage('Docker build/push') {
      docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
        def app = docker.build("${image_name}:${commit_id}", '.').push()
      }
    }

    stage('Initialize Keptn Project') {
        // Initialize the Keptn Project - ensures the Keptn Project is created with the passed shipyard
        keptn.keptnInit project:"${project}", service:"${service}", stage:"${firststage}", monitoring: "dynatrace", shipyard: ".keptn/shipyard.yaml"
    }

    stage('Add files to Keptn Project') {
        // Upload quality gate files
        //keptn.keptnAddResources('keptn/dynatrace/dynatrace.conf.yaml','dynatrace/dynatrace.conf.yaml')
        // Upload SLI and SLO files
        keptn.keptnAddResources('.keptn/dynatrace/sli.yaml','dynatrace/sli.yaml')
        keptn.keptnAddResources('.keptn/slo.yaml','slo.yaml')

        // Package Helm Chart .tgz
        sh 'tar -cvzf .keptn/helm/hello-service.tgz -C .keptn/helm/ hello-service'

        // Add Helm Chart for hello-service
        keptn.keptnAddResources('.keptn/helm/hello-service.tgz', 'helm/hello-service.tgz')
        // ToDo: Add helm chart for other stages too
        // Depends on https://github.com/keptn-sandbox/keptn-jenkins-library/issues/60
    }

    stage('Trigger Delivery') {
        def keptnContext = keptn.sendDeliveryTriggeredEvent image:"${image_name}:${commit_id}"
        String keptn_bridge = env.KEPTN_BRIDGE
        echo "Open Keptns Bridge: ${keptn_bridge}/trace/${keptnContext}"
    }

    stage('Wait for Result') {
        echo "Waiting until Keptn is done and returns the results"
        def result = keptn.waitForEvaluationDoneEvent setBuildResult:true, waitTime:5
        echo "${result}"
    }
}
```
