### ISSUE TITLE
sendDeliveryTriggeredEvent does not trigger any delivery

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-sandbox/keptn-jenkins-library#54]
With keptn-shared-library @ v5.0, the `sendDeliveryTriggeredEvent` function is not working as documented.

We end up not getting any sequence in Keptn:
![image](https://user-images.githubusercontent.com/56065213/140767181-0f16cd0a-4e59-4095-af07-82fdc17a64d8.png)

*Pipeline*:
```
@Library('keptn-library@5.0')_
def keptn = new sh.keptn.Keptn()


node('jenkins-slave') {

    def commit_id

    def project = "nodejs-example"
    def service = "hello-service"
    def firststage = "dev"

    stage('Preparation') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"                        
        commit_id = readFile('.git/commit-id').trim()
    }

    stage('Docker build/push') {
      docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
        def app = docker.build("christiankreuzbergerdtx/docker-nodejs-demo:${commit_id}", '.').push()
      }
    }

    stage('Initialize Keptn') {
        // Initialize the Keptn Project - ensures the Keptn Project is created with the passed shipyard
        keptn.keptnInit project:"${project}", service:"${service}", stage:"${firststage}", monitoring: "dynatrace", shipyard: ".keptn/shipyard.yaml"

        // Upload quality gate files
        //keptn.keptnAddResources('keptn/dynatrace/dynatrace.conf.yaml','dynatrace/dynatrace.conf.yaml')
        // Upload SLI and SLO files
        keptn.keptnAddResources('.keptn/dynatrace/sli.yaml','dynatrace/sli.yaml')
        keptn.keptnAddResources('.keptn/slo.yaml','slo.yaml')

        // Create Helm Chart .tgz
        sh 'tar cfvz .keptn/helm/hello-service.tgz .keptn/helm/hello-service'

        // Add Helm Chart for hello-service
        keptn.keptnAddResources('.keptn/helm/hello-service.tgz', 'helm/hello-service.tgz')
    }

    stage('Trigger Delivery') {
        def keptnContext = keptn.sendDeliveryTriggeredEvent image:"christiankreuzbergerdtx/docker-nodejs-demo:${commit_id}"
        String keptn_bridge = env.KEPTN_BRIDGE
        echo "Open Keptns Bridge: ${keptn_bridge}/trace/${keptnContext}"
    }

    stage('Wait for Result') {
        echo "Waiting until Keptn is done and returns the results"
        def result = keptn.waitForEvaluationDoneEvent setBuildResult:true, waitTime:5
        echo "${result}"
    }
}
```

**shipyard.yaml**
```
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
            - name: "test"
              properties:
                teststrategy: "functional"
            - name: "evaluation"

    - name: "hardening"
      triggeredOn:
        - event: "dev.delivery.finished"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"

    - name: "production"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "hardening.delivery.finished"
          tasks:
            - name: "approval"
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green"
            - name: "release"

```
